### PR TITLE
feat: support "LaunchOptions" for puppeteer

### PR DESCRIPTION
**Pull request by sososoyoung**
在部分 arm 设备上 puppeteer 目录下 chrome 启动报错，希望支持 executablePath option, 可以自由指定 chromium 路径。

Same: #45

### CODE REVIEW

**Comment by sososoyoung** [comment]
I added a new option: ```puppetOptions.endpoint```

**Comment by huan** [comment]
@sososoyoung Sorry, the endpoint should not be put at there.

Please read my review more carefully and refer to the PR as I mentioned, I believe we need to modify more files from this PR.

Also, I had two suggestions for you, It would be terrific if you can have any feedback to me.

Thank you very much.

**Comment by sososoyoung** [comment]
I'm so sorry for the inconvenience. It seem that i have to change ```wechaty-puppet``` if i want to add a new option to PuppetOptions. So, i removed ```launchOptions``` temporarily.

**Comment by huan** [comment]
Thank you very much, the `endpoint` part looks good to me.

And about the `PuppetOptions`: I had just added support to add any options key to it, and it should be available on `wechaty-puppet@0.15.20` or above.

Please upgrade `wechaty-puppet` dependence to v0.15.20 and make another pull request to support this will be welcome.

**Comment by huan** [comment]
This PR should be available on `wechaty-puppet-puppeteer@0.17.17` or above.

**Comment by huan** [comment]
I had just invited you to the Chatie Contributor Team, please accept it from <https://github.com/Chatie>

> You've invited jason to Chatie! They'll be receiving an email shortly. They can also visit https://github.com/Chatie to accept the invitation.

Thank you for your great contribution!

**Comment by sososoyoung** [comment]
> Thank you very much, the `endpoint` part looks good to me.
> 
> And about the `PuppetOptions`: I had just added support to add any options key to it, and it should be available on `wechaty-puppet@0.15.20` or above.
> 
> Please upgrade `wechaty-puppet` dependence to v0.15.20 or above, and make another pull request to support this will be welcome.

I had update to `wechaty-puppet@0.15.20` and add the `launchOptions `, do I need to creat a new pull?

**Comment by huan** [comment]
Yes, please create a new pull request for your `lanchOptions` enhancement.

Thank you very much!

**Pull request merged**
