### PR TITLE
Fix change room topic error

### PR DESCRIPTION
**Pull request by hoo-ge**
Fix:
1. retry.d.ts version error
2. change room topic erro

### CODE REVIEW

**Comment by huan** [comment]
Thanks for the PR!

Could you please refer to the related issue number, and describe the modifications in your PR so that we could be able to start reviewing it?

**Comment by hoo-ge** [comment]
For issue #73 

1. Downgrade npm @types/retry to 0.10.1
2. Modify the problem of getting the username error

**Comment by huan** [comment]
Thanks for updating!

Next step:

Please get at least one approvement from our developer community(or contributors) before I could be able to make sure to merge it to the mast branch!

**Comment by huan** [comment]
@TbhT thank you very much for approving this PR, it's very valuable!

**Pull request merged**
