### PR TITLE
fix hookRecalledMsgProcess reference exception

### PR DESCRIPTION
**Pull request by seanxlliu**
chatFactory context was not passed into oldRecalledMsgProcess, so the exception is thrown in the original function.

### CODE REVIEW

**Comment by seanxlliu** [comment]
@huan by merging this PR, a recalled message will trigger the 'message' event with the same type and content of original message.
i.e. 

1. the client sends 'test'
2. wechaty trigger: 'message' => { text: test, type: text }
3. the client recalls 'test'
4. wechaty trigger 'message' => { text: test, type: text } again

**Comment by huan** [comment]
Could you please only `try {} catch () {}` the `oldRecalledMsgProcess.call(chatFactory, msg)` instead of the whole code block?

After that, I'll merge it and let's begin discussing how to design and implement the `RECALL` behavior.

**Comment by seanxlliu** [comment]
Done. Changed try/catch block scope and change the log message.

**Comment by huan** [comment]
Awesome, thank you very much for the contribution!

**Pull request merged**
