### PR TITLE
Update for cnpm's change.

### PR DESCRIPTION
**Pull request by solarhell**
Update for cnpm's change.

### CODE REVIEW

**Comment by huan** [comment]
Thanks for the contribution!

Could you please file an issue related to this PR and describe the details about why we need this change?

And please get at least one approvement from our contributes before I could be able to merge it.

**Comment by solarhell** [comment]
see https://github.com/cnpm/cnpmjs.org/issues/1246#issuecomment-449783563

**Comment by huan** [comment]
@solarhell Thanks for the link, it's very useful.

I'll merge this PR after it gets an approvement from our contributors, thank you very much!

**Comment by huan** [comment]
@windmemory Thanks for the approvement, merged!

**Pull request merged**
